config/routes.rb
Rails.application.routes.draw do
  
  get 'profile/My_profile'
  
  resources :posts do
  	resources :comments
  end
   root 'posts#index' 


  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
  public
  def author
  	return User.find_by(id: self.user_id).username
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :delete_all
  validates :body, presence: true

public

  # def addGrade(grade,current_user_id)
  # 	com=self.comments.find_by(user_id: current_user_id)
  # 	if(com.size==0)
  # 		com=Comment.create(user_id: current_user_id, post_id: self.id, status: grade);
  # 		return;
  # 	else
  # 		if (grade==1&&com.first.status==0||grade==-1&&com.first.status==0)
  # 			com.each do |c|
  # 				c.status=grade;
  # 			end
  # 		else
  # 			com.each do |c|
  # 				c.status=0;
  # 			end
  # 		end
  # 	end
  # end
  # def likeCount
  # 	com=self.comments.all.sort_by { |e| e.user_id }
  # 	i=0
  # 	count=0
  # 	while(i<com.length-1)
  # 		temp=com[i];
  # 		if(temp.user_id!=com[i+1].user_id)
  # 			count+=1
  # 		end
  # 		i+=1;
  # 	end
  # 	return count;
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts, :dependent => :delete_all
has_many :comments,:dependent => :delete_all

  validates :username, presence: true
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :remember_me])#if u registrated u must write these params
  	devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])#if u sign in to ur account u must write these params
  	devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :remember_me, :Avatar])
  end
  def after_sign_in_path_for(resource)
  posts_path
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  def create
    @p=Post.find(params[:post_id])
    @c=@p.comments.new(params.require(:comment).permit(:body,:status))
    @c.user_id=current_user.id
    @c.save
    redirect_to post_path(@p)
  end

  def destroy
    @p = Post.find(params[:post_id])
    if current_user.id==@p.user_id
      @c = @p.comments.find(params[:id])
      @c.destroy
      redirect_to post_path(@p)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  #before_filter :authenticate_user!, except => [:show, :index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @p=Post.find(params[:id])
   if current_user!=nil&&current_user.id!=@p.user_id 
    @p.isRead=true
    @p.save
    end
    @author=User.find_by(id: @p.user_id).username
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id
    @post.isRead=false
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if @post.user_id==current_user.id
     @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  end

public
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image, :isRead, :user_id)
    end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	def My_profile
		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/comments/_comment.html.erb
<h2><%= comment.author %>:<h2>
<h3><%= comment.body%></h3>
<%= link_to 'Destroy',[comment.post,comment],method: :delete, data: {confirm:'Are you sure?'}%>

app/views/comments/_form.html.erb
<%= form_for([@p,@p.comments.build]) do |form| %>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<div>
      кнопки входу/виходу і реєстрації:
       <% if user_signed_in? %>
           <span>Здравствуйте, <%= current_user.email %></span>
          <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
      <% else %>
          <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
      <% end %>
  </div>
  <%=link_to 'Home',root_path%>
  <%=link_to 'My Profile',profile_My_profile_path%>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :post_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th>Isread</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.image %></td>
        <td><%= post.isRead %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Image:</strong>
  <img src=<%= @post.image %> alt=""> 
</p>

<p>
  <strong>Isread:</strong>
  <%= @post.isRead %>
</p>

<p>
  <strong>User:</strong>
  <%= @author %>
</p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<h3>Comments( <%=@post.comments.length%>)</h3>

<%=render @post.comments %>

<h3>Add comment</h3>
<%= render 'comments/form' %>